### ISSUE TITLE
Tracking issue for AnyMoE

### ISSUE THREAD

**Issue by EricLBuehler** [EricLBuehler/mistral.rs#514]
This is a tracking issue for the development of AnyMoE, which will be broken up into several PRs.

- [x] Core functionality, plain models, all APIs: #476
- [x] Support for vision models: #515
- [x] Support saving and loading gating layer: #519 
- [x] #528
- [x] #529

**Comment by EricLBuehler** [comment]
Done!
